HW11/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace HW11.Models
{
    public class Contact
    {
        [Required]
        public string? Name { get; set; }

        [Required]
        public string? PhoneNumber { get; set; }

        public string? AlternativePhoneNumber { get; set; }

        [Required]
        public string? Email { get; set; }

        [DataType(DataType.MultilineText)]
        public string? Description { get; set; }

    }
}

HW11/Models/ErrorViewModel.cs
namespace HW11.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HW11/Models/Note.cs
using System.ComponentModel.DataAnnotations;

namespace HW11.Models
{
    public class Note
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Title { get; set; }

        [DataType(DataType.MultilineText)]
        public string? Text { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; }

        public string? Tags { get; set; }
    }
}

HW11/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace HW11.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HW11/Controllers/HomeController.cs
using HW11.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HW11.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HW11/Controllers/NoteController.cs
using HW11.Data;
using HW11.Models;
using Microsoft.AspNetCore.Mvc;

namespace HW11.Controllers
{
    public class NoteController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NoteController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<Note> notes = _context.Notes;

            return View(notes);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Note note)
        {
            if (ModelState.IsValid)
            {
                _context.Notes.Add(note);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(note);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var note = _context.Notes.Find(id);

            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Note note)
        {
            if (ModelState.IsValid)
            {
                _context.Notes.Update(note);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(note);
        }


    }
}

HW11/Views/Contact/Index.cshtml
@{
    ViewData["Title"] = "Contact";
}
@{
    Contact contact = new Contact();
    contact.Name = "Olga";
    contact.PhoneNumber = "+380999999999";
    contact.Email = "111@gmail.com";
    contact.Description = " Head of the youth center";
}
<div>
    <h1>Contact</h1>
</div>
<div>
    <h6>Name:</h6>
    @contact.Name;
    <br /><br />
    <h6>Phone Number:</h6>
    @contact.PhoneNumber;
    <br /><br />
    <h6>Alternative Phone Number:</h6>
    @contact.AlternativePhoneNumber;
    <br /><br />
    <h6>Email:</h6>
    @contact.Email;
    <br /><br />
    <h6>Description:</h6>
    @contact.Description;
    <br /><br />
</div>

HW11/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HW11/Views/Note/Create.cshtml
@model Note


<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Add Note</h2>
    </div>

    <form method="post">
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Title">Title</label>
                <input type="text" class="form-control mb-3" asp-for="Title" placeholder="Enter Title" required>
                <span asp-validation-for="Title" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Text">Text</label>
                <input type="text" class="form-control mb-3" asp-for="Title" placeholder="Enter Text">
                <span asp-validation-for="Title" class=" alert-danger"></span>
            </div><div class="form-group col-md-6">
                <label asp-for="Tags">Tags</label>
                <input type="text" class="form-control mb-3" asp-for="Tags" placeholder="Enter Tags">
                <span asp-validation-for="Title" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="CreatedAt">Created At</label>
                <input type="datetime-local" class="form-control" asp-for="CreatedAt">
                <span asp-validation-for="CreatedAt" class=" alert-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Save</button>
        <a asp-controller="Note" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To List</a>
    </form>

</div>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

HW11/Views/Note/Edit.cshtml
@model Note

<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Edit Note</h2>
    </div>

    <form method="post"  asp-action="Edit">
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Title">Title</label>
                <input type="text" class="form-control mb-3" asp-for="Title" placeholder="Enter Title" required>
                <span asp-validation-for="Title" class="alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Text">Text</label>
                <input type="text" class="form-control mb-3" asp-for="Title" placeholder="Enter Text">
                <span asp-validation-for="Title" class=" alert-danger"></span>
            </div><div class="form-group col-md-6">
                <label asp-for="Tags">Tags</label>
                <input type="text" class="form-control mb-3" asp-for="Tags" placeholder="Enter Tags">
                <span asp-validation-for="Title" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="CreatedAt">Created At</label>
                <input type="datetime-local" class="form-control" asp-for="CreatedAt">
                <span asp-validation-for="CreatedAt" class=" alert-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Update</button>
        <a asp-controller="Note" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To List</a>
    </form>

</div>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

HW11/Views/Note/Index.cshtml
@model IEnumerable<Note>
@{
    ViewData["Title"] = "Note";
}

<div>
    <h1>Notes</h1>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Text</th>
                <th>Tags</th>
                <th>Created At</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var note in Model)
            {
                <tr>
                    <td width="15%">@note.Title</td>
                    <td width="50%">@note.Tags</td>
                    <td width ="15%">@note.Tags</td>
                    <td width ="15%">@note.CreatedAt</td>
                    <td>
                        <div>
                            <span>
                                <a asp-controller="Note" asp-action="Edit" asp-route-id="@note.Id" class="btn btn-sm btn-primary"><i class="bi bi-pencil-square"></i>Edit</a>
                            </span>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="col mb-3">
        <a asp-controller="Note" asp-action="Create" class="btn btn-lg btn-primary"><i class="bi bi-file-plus-fill"></i>Add</a>
    </div>
</div>

HW11/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HW11</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HW11.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HW11</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Index">Note</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HW11 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>